// <auto-generated />
using System;
using AcmeOrder.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeOrder.Migrations.Sqlite
{
    [DbContext(typeof(SqliteOrderContext))]
    [Migration("20260611193200_UpdateDateDefaultToSql")]
    partial class UpdateDateDefaultToSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AcmeOrder.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Card")
                        .HasColumnType("TEXT")
                        .HasColumnName("card");

                    b.Property<string>("Cart")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Delivery")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery");

                    b.Property<string>("Email")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("Paid")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("paid");

                    b.Property<string>("Total")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<string>("UserId")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("order", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
